[package]
name = "day_12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cache-macro = { git = "https://github.com/takashiidobe/cache-macro" }
lazy_static = "1.4.0"
lru-cache = "0.1.2"
